# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build wechat-pay`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t wechat-pay`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system wechat-pay && \
          adduser --system -G wechat-pay wechat-pay

COPY dist/wechat-pay wechat-pay/
RUN chown -R wechat-pay:wechat-pay .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix wechat-pay --omit=dev -f install

CMD [ "node", "wechat-pay" ]
